FROM node:16.16.0-alpine

WORKDIR /app
COPY . .

RUN apk add --no-cache tzdata && cp /usr/share/zoneinfo/Asia/Bangkok /etc/localtime && rm yarn.lock && yarn && yarn cache clean

EXPOSE 3000
CMD [ "yarn", "start" ]
